export const dummyMetrics = [
    {
        id: 'dummy-1',
        metricName: 'Monthly Recurring Revenue',
        uuid: 'MRR-2024-001',
        domain: 'Finance',
        category: 'Revenue',
        type: 'Sum',
        status: 'Certified',
        version: '2.1',
        businessOwner: 'Sarah Johnson',
        technicalSteward: 'Mike Chen',
        description: 'Total predictable revenue generated from all active subscriptions normalized to a monthly amount',
        businessPurpose: 'Track recurring revenue growth and predict future revenue streams',
        useCases: 'Financial forecasting, investor reporting, growth analysis',
        exclusionScenarios: 'One-time payments, setup fees, refunds',
        unitOfMeasure: 'USD',
        interpretationRules: 'Round to nearest dollar, exclude negative values, calculate at month end',
        abstractInputs: 'subscription_amount, billing_frequency',
        aggregationLogic: 'SUM(subscription_amount * (12 / billing_frequency)) / 12',
        windowLogic: 'Monthly rolling window',
        filterRules: 'WHERE subscription_status = "active" AND billing_frequency IN (1, 3, 6, 12)',
        selectedColumns: ['subscription_amount', 'billing_frequency'],
        createdAt: '2024-01-15T10:30:00Z',
        approvedBy: 'Admin',
        approvedAt: '2024-01-16T14:20:00Z'
    },
    {
        id: 'dummy-2',
        metricName: 'Customer Churn Rate',
        uuid: 'CHR-2024-002',
        domain: 'Customer Success',
        category: 'Engagement',
        type: 'Ratio',
        status: 'Certified',
        version: '1.5',
        businessOwner: 'Emily Davis',
        technicalSteward: 'Alex Kumar',
        description: 'Percentage of customers who cancel their subscription within a given time period',
        businessPurpose: 'Monitor customer retention and identify at-risk segments',
        useCases: 'Retention analysis, customer health scoring, product improvement prioritization',
        exclusionScenarios: 'Trial users, paused subscriptions, involuntary churn',
        unitOfMeasure: 'Percentage',
        interpretationRules: 'Round to 2 decimal places, report monthly, exclude first 30 days',
        abstractInputs: 'churned_customers, total_customers',
        aggregationLogic: '(COUNT(churned_customers) / COUNT(total_customers)) * 100',
        windowLogic: 'Monthly cohort analysis',
        filterRules: 'WHERE subscription_age > 30 AND churn_type = "voluntary"',
        selectedColumns: ['customer_id', 'churn_date', 'subscription_start'],
        createdAt: '2024-02-10T09:15:00Z',
        approvedBy: 'Admin',
        approvedAt: '2024-02-11T11:45:00Z'
    },
    {
        id: 'dummy-3',
        metricName: 'Average Order Value',
        uuid: 'AOV-2024-003',
        domain: 'Sales',
        category: 'Revenue',
        type: 'Average',
        status: 'Certified',
        version: '3.0',
        businessOwner: 'Robert Martinez',
        technicalSteward: 'Lisa Wang',
        description: 'Average monetary value of each order placed by customers',
        businessPurpose: 'Measure customer spending patterns and optimize pricing strategies',
        useCases: 'Pricing optimization, marketing campaign effectiveness, customer segmentation',
        exclusionScenarios: 'Cancelled orders, refunded transactions, test orders',
        unitOfMeasure: 'USD',
        interpretationRules: 'Round to 2 decimal places, exclude outliers above 99th percentile',
        abstractInputs: 'order_total, order_count',
        aggregationLogic: 'SUM(order_total) / COUNT(DISTINCT order_id)',
        windowLogic: 'Rolling 30-day window',
        filterRules: 'WHERE order_status = "completed" AND order_total > 0',
        selectedColumns: ['order_id', 'order_total', 'order_date'],
        createdAt: '2024-03-05T14:20:00Z',
        approvedBy: 'Admin',
        approvedAt: '2024-03-06T10:30:00Z'
    },
    {
        id: 'dummy-4',
        metricName: 'Net Promoter Score',
        uuid: 'NPS-2024-004',
        domain: 'Customer Experience',
        category: 'Engagement',
        type: 'Derived',
        status: 'In Review',
        version: '1.0',
        businessOwner: 'Jennifer Lee',
        technicalSteward: 'David Park',
        description: 'Customer loyalty and satisfaction metric based on likelihood to recommend',
        businessPurpose: 'Measure overall customer satisfaction and brand advocacy',
        useCases: 'Customer satisfaction tracking, competitive benchmarking, product roadmap prioritization',
        exclusionScenarios: 'Incomplete surveys, duplicate responses, internal users',
        unitOfMeasure: 'Score (-100 to 100)',
        interpretationRules: 'Calculate as % promoters minus % detractors, round to integer',
        abstractInputs: 'survey_score, response_count',
        aggregationLogic: '((COUNT(promoters) - COUNT(detractors)) / COUNT(total_responses)) * 100',
        windowLogic: 'Quarterly measurement',
        filterRules: 'WHERE survey_completed = true AND score BETWEEN 0 AND 10',
        selectedColumns: ['response_id', 'score', 'survey_date'],
        createdAt: '2024-04-12T16:45:00Z',
        approvedBy: null,
        approvedAt: null
    },
    {
        id: 'dummy-5',
        metricName: 'Operational Risk Score',
        uuid: 'ORS-2024-005',
        domain: 'Risk Management',
        category: 'Risk',
        type: 'Windowed',
        status: 'Certified',
        version: '2.3',
        businessOwner: 'Thomas Anderson',
        technicalSteward: 'Rachel Green',
        description: 'Composite score measuring operational risk exposure across key business processes',
        businessPurpose: 'Identify and mitigate operational risks before they impact business continuity',
        useCases: 'Risk assessment, compliance reporting, resource allocation',
        exclusionScenarios: 'External risks, strategic risks, low-impact incidents',
        unitOfMeasure: 'Score (0-100)',
        interpretationRules: 'Higher score indicates higher risk, update weekly, escalate above 75',
        abstractInputs: 'incident_count, severity_weight, exposure_time',
        aggregationLogic: 'SUM(incident_count * severity_weight * exposure_time) / total_processes',
        windowLogic: '7-day rolling window with decay factor',
        filterRules: 'WHERE incident_type = "operational" AND severity >= "medium"',
        selectedColumns: ['incident_id', 'severity', 'process_id', 'timestamp'],
        createdAt: '2024-05-20T08:00:00Z',
        approvedBy: 'Admin',
        approvedAt: '2024-05-21T13:15:00Z'
    }
]
